# NumPy – Numerical Python
## 1. Why Learn NumPy?

#### What is it?

NumPy is a powerful Python library for numerical computations. It provides fast and memory-efficient multi-dimensional arrays.

#### Why we need it?

1.Pure Python lists are slow for large datasets.

2.NumPy arrays are optimized for speed and vectorized operations.

3.Most Data Science & Machine Learning libraries (like Pandas, Scikit-Learn, TensorFlow) are built on top of NumPy.

#### Where is it used?

1.Data Analysis

2.Machine Learning & Deep Learning

3.Image Processing (OpenCV, PIL use NumPy arrays)

5.Scientific Computing & Simulations


In [1]:
import numpy as np


In [3]:

## 3. Arrays vs Python Lists
import numpy as np
import time

# Python list
py_list = [i for i in range(1000000)]

# NumPy array
np_array = np.arange(1000000)

# Time comparison
start = time.time()
sum(py_list)
print("Python list sum time:", time.time() - start)

start = time.time()
np.sum(np_array)
print("NumPy array sum time:", time.time() - start)




Python list sum time: 0.008003711700439453
NumPy array sum time: 0.0020112991333007812


In [6]:
np.arange(0, 10, 2)  # Output: array([0, 2, 4, 6, 8])


array([0, 2, 4, 6, 8])

In [35]:
np.linspace(0, 1, 6)  # Output: array([0. , 0.25, 0.5 , 0.75, 1. ])


array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [ ]:
# From list 
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)

# Zeros and Ones
print("Zeros:", np.zeros((2,3)))
print("Ones:", np.ones((2,3)))

# Arange and Linspace
print("Arange:", np.arange(0, 10, 2))
print("Linspace:", np.linspace(0, 1, 5))

Array: [1 2 3 4 5]
Zeros: [[0. 0. 0.]
 [0. 0. 0.]]
Ones: [[1. 1. 1.]
 [1. 1. 1.]]
Arange: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]


In [9]:
ar=np.array([2,4,5,6])

In [10]:
print(ar)

[2 4 5 6]


In [11]:
arr=np.zeros((2,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [12]:
arr=np.ones((5,2))
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [13]:
print(np.arange(2,6,2))

[2 4]


In [16]:
ar=np.array([[1,2,3],[3,4,5]])
print("Array shape",ar.shape)

Array shape (2, 3)


In [17]:
print("array type",ar.dtype)

array type int32


In [18]:
print("Array size:", ar.size)
print("Array ndim:", ar.ndim)

Array size: 6
Array ndim: 2


In [19]:
## 6. Indexing and Slicing
arr = np.array([10,20,30,40,50])
print("Element at index 2:", arr[2])
print("Elements from index 1 to 3:", arr[1:4])
print("Elements at indices 0, 2, 4:", arr[[0,2,4]])
print("Every second element:", arr[::2])
print("Reversed array:", arr[::-1])
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix:\n", matrix)
print("Matrix shape:", matrix.shape)
print("Matrix dtype:", matrix.dtype)
print("Matrix size:", matrix.size)
print("Matrix ndim:", matrix.ndim)
print(matrix[0,1]) # element at row 0, col 1
print(matrix[1,:]) # entire row 1
print(matrix[:,2]) # entire col 2
# Matrix operations
print("Transpose:\n", matrix.T)
print("Sum of all elements:", np.sum(matrix))
print("Sum of each column:", np.sum(matrix, axis=0))
print("Sum of each row:", np.sum(matrix, axis=1))
print("Mean of all elements:", np.mean(matrix))
print("Mean of each column:", np.mean(matrix, axis=0))
print("Mean of each row:", np.mean(matrix, axis=1))
print("Element-wise multiplication:\n", matrix * 2)
print("Matrix multiplication:\n", np.dot(matrix, matrix))  

Element at index 2: 30
Elements from index 1 to 3: [20 30 40]
Elements at indices 0, 2, 4: [10 30 50]
Every second element: [10 30 50]
Reversed array: [50 40 30 20 10]
Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix shape: (3, 3)
Matrix dtype: int32
Matrix size: 9
Matrix ndim: 2
2
[4 5 6]
[3 6 9]
Transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Sum of all elements: 45
Sum of each column: [12 15 18]
Sum of each row: [ 6 15 24]
Mean of all elements: 5.0
Mean of each column: [4. 5. 6.]
Mean of each row: [2. 5. 8.]
Element-wise multiplication:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Matrix multiplication:
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [20]:
a=np.array([1,2,3])
b=np.array([3,4,5])
print('a+b:',a+b)
print('a*b:',a*b)
print('a+10:',a+10)
print('a*2:',a*2)

a+b: [4 6 8]
a*b: [ 3  8 15]
a+10: [11 12 13]
a*2: [2 4 6]


## 8. Mathematical Functions

In [ ]:
## 8. Mathematical Functions
arr = np.array([1,2,3,4,5])
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))
print("Standard Deviation:", np.std(arr))
print("Variance:", np.var(arr))
print("Square Root:", np.sqrt(arr))
print("Exponential:", np.exp(arr))
print("Logarithm:", np.log(arr))



Sum: 15
Mean: 3.0
Max: 5
Min: 1
Standard Deviation: 1.4142135623730951
Variance: 2.0
Square Root: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Logarithm: [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped array (3x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flattened array: [ 1  2  3  4  5  6  7  8  9 10 11 12]


## 9. Reshaping Arrays


In [22]:
arr = np.arange(1, 13)
reshaped = arr.reshape((3,4))
print("Original array:", arr)
print("Reshaped array (3x4):\n", reshaped)
flattened = reshaped.flatten()
print("Flattened array:", flattened)


Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped array (3x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flattened array: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [23]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
print(a[1,:])

[4 5 6]


In [34]:
#generate randon 5x5 matrix and find its max and min value
a=np.random.rand(5,5)
b=np.random.randint(1,10,(5,5))
print(a)
print(b)

[[0.56380044 0.29993749 0.5553744  0.35146165 0.27084436]
 [0.46065719 0.27781238 0.54833716 0.57345385 0.85096875]
 [0.11426753 0.98808519 0.01555837 0.76931433 0.75009594]
 [0.2403515  0.39573321 0.51732549 0.85434637 0.46159802]
 [0.07677194 0.3843314  0.09546727 0.33179771 0.65603866]]
[[1 6 5 7 5]
 [4 8 7 9 5]
 [9 4 7 7 6]
 [4 9 6 7 1]
 [1 3 7 3 3]]


In [33]:
print(np.max(a))
print(np.min(a))

0.9704447111890093
0.058173211045230766
